### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ageil** [tempelkoderne/pop#1]
- [ ] \(need) Intelligent computerGuess
- [ ] \(need) Samlende gameFlow
- [ ] \(need) Rapport
- [ ] \(nice) Oprydning i global scope
- [X] \(nice) Rekursiv validate uden histogrammer
